from __future__ import annotations

from io import StringIO

from ase.io import read

from phonoflow.analysis.bandpath import get_band_path, high_symmetry_path_metadata


GA2O3_POSCAR = """Generated by VASPKIT code
   1.00000000000000
     2.5319150301581099    1.4617992192404365    4.5445030339512051
    -2.5319108859700088    1.4618018938054052    4.5444998718385072
     0.0000043848806745   -2.9235981301322540    4.5445004813591980
   Ga   O
     4     6
Direct
  0.8558409549719943  0.8558389837477949  0.8558406171901741
  0.6441617906527634  0.6441610354000130  0.6441594010986916
  0.1441600804183029  0.1441618040442012  0.1441601347464034
  0.3558401393554071  0.3558399477645164  0.3558398139339909
  0.7499975572744466  0.4470110440060614  0.0529908307539275
  0.4470102729033709  0.0529894026863298  0.7499981567600069
  0.0529901352188930  0.7499990451812184  0.4470099754081447
  0.2500002883269364  0.5529895081853311  0.9470110212732747
  0.9470105097907044  0.2500000892177990  0.5529877100686570
  0.5529882710871727  0.9470091397667377  0.2500023387667280
"""


def test_core_bandpath_matches_seekpath_full_path_for_distorted_ga2o3() -> None:
    atoms = read(StringIO(GA2O3_POSCAR), format="vasp")

    band_path = get_band_path(atoms)
    metadata = high_symmetry_path_metadata(band_path.segments, source=band_path.source)
    display = metadata["display"]

    assert display.startswith("Γ — X | Y — Γ | Γ — Z")
    assert "X'" in display
    assert "V'" in display
    assert "Γ — T | T — H_2" not in display
    assert metadata["symprec"] == 1e-5
    assert metadata["with_time_reversal"] is False
